

<div style="max-width: 300px; margin: 0 auto">
    <?php echo $this->tag->form(["signup/register"]); ?>

        <h1 class="h3 mb-3 font-weight-normal">
          Cadastro de usuários
        </h1>
        <div class="form-group">
            <label for="inputEmail">
                Nome: 
            </label>
            <?php echo $this->tag->textField([
                'nome', 
                "class" => "form-control", 
                'placeholder' => 'Seu nome', 
                'type' => 'text'
            ]); ?>
        </div>

        <div class="form-group">
            <label for="inputEmail">
                Email
            </label>
            <?php echo $this->tag->textField([
                'email', 
                "class" => "form-control", 
                'placeholder' => 'Seu e-mail', 
                'type' => 'email'
            ]); ?>
        </div>

        <div class="form-group">
            <label for="inputPassword">
                Password
            </label>
            <?php echo $this->tag->passwordField([
                'password', 
                "class" => "form-control", 
                'placeholder' => 'senha', 
                'type' => 'password'
            ]); ?>
        </div>      

        <div class="form-group">
            <label for="inputPassword">
                Repita a senha
            </label>
            <?php echo $this->tag->passwordField([
                'repassword', 
                "class" => "form-control", 
                'placeholder' => 'senha', 
                'type' => 'password'
            ]); ?>
        </div>      

        <?php echo $this->tag->submitButton([
            "Signup", 
            'class' => 'btn btn-lg btn-primary btn-block',
            'style' => 'margin-bottom: 20px'
        ]); ?>

    </form>
    
</div>
